import React from "react";
import { NextPage } from "next";
import Head from "next/head";
import "@/styles/globals.css";
import NavBar from "@/components/common/NavBar";
import Footer from "@/components/common/Footer";

interface WebLayoutProps {
  children: React.ReactNode;
  title?: string;
  description?: string;
}

const WebLayout: NextPage<WebLayoutProps> = ({
  children,
  title,
  description,
}) => {
  const pageTitle = title ? `Al-Burraq - ${title}` : "Al-Burraq";

  return (
    <html>
      <Head>
        <title>{pageTitle}</title>
        <meta
          name="description"
          content={description || "Generated by create next app"}
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="flex flex-col min-h-screen">
        <NavBar />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
};

export default WebLayout;
