import { Metadata } from "next";
import "@/styles/globals.css";
import NavBar from "@/components/common/NavBar";
import Footer from "@/components/common/Footer";

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <NavBar />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
};

export const metadata: Metadata = {
  title: "Al-Burraq",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default RootLayout;
