// import { Metadata } from "next";
import "@/styles/globals.css";
import NavBar from "@/components/common/NavBar";
import Footer from "@/components/common/Footer";

interface WebLayoutProps {
  children: React.ReactNode;
  title?: string;
  description?: string;
}

const WebLayout = ({ children, title, description }: WebLayoutProps) => {
  const pageTitle = title ? `Al-Burraq - ${title}` : "Al-Burraq";

  return (
    <html lang="en">
      <head>
        <title>{pageTitle}</title>
        <meta
          name="description"
          content={description || "Generated by create next app"}
        />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="flex flex-col min-h-screen">
        <main>
          <NavBar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
};

// export const metadata: Metadata = {
//   title: {pageTitle},
//   description: "Generated by create next app",
//   icons: {
//     icon: "/favicon.ico",
//   },
// };

export default WebLayout;
