// import { Metadata } from "next";
import "@/styles/globals.css";
import Head from "next/head";
import NavBar from "@/components/common/NavBar";
import Footer from "@/components/common/Footer";

interface WebLayoutProps {
  children: React.ReactNode;
  title?: string;
  description?: string;
}

const WebLayout = ({ children, title, description }: WebLayoutProps) => {
  const pageTitle = title ? `Al-Burraq - ${title}` : "Al-Burraq";

  return (
    <>
      <html lang="en">
        <Head>
          <title>{pageTitle}</title>
          <meta
            name="description"
            content={description || "Generated by create next app"}
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <body className="flex flex-col min-h-screen">
          <main>
            <NavBar />
            {children}
            <Footer />
          </main>
        </body>
      </html>
    </>
  );
};

// export const metadata: Metadata = {
//   title: {pageTitle},
//   description: "Generated by create next app",
//   icons: {
//     icon: "/favicon.ico",
//   },
// };

export default WebLayout;
